### ISSUE TITLE
Feedback on Proposal

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Taracyc_Ocean_Virus_Analysis#12]
@HarjyotKaur and @heathervant , you have chosen an interesting question and I look forward to reading more on your analysis. This analysis will be very useful for me personally as I have such little knowledge on biology topics and I want to change that :) Here are some improvement points and minor suggestions for your project.

**Reasoning**

- Keep in mind that your readme is the landing page for someone examining your analysis. Therefore, you can do some additions that would make the readme more informative and intriguing for a visitor. In particular, you can include a brief introduction about the context and your motivation to do such analysis. Then, you can introduce your question and explain the data as you have done already.

**Mechanics**

- Your names should not be a part of the project repository name. The name should be more descriptive of the project. For example, simply "taracyc_analysis" can be a great name for your project. I would also recommend taking "DSCI_522" out of the name of your project. But if you like it this way, no problem. You should also update your readme title based on the changes you make in the repository title.

- Always include a link when you point your readers to a specific file and/or folder in your repository. For example, include the link to the file within the sentence "For further information, the steps followed for downloading this data have been outlined in the same repository."

- The screenshot of the data import is useful, but I would suggest using a code chunk for the code and printing output as a table. I believe it might look more professional that way. You can do this easily by creating the README file as an R markdown and knitting as github_document.

- I see that you have found a solution within Github to store the large data set needed for your analysis. The data repository is well-organized and explains the data extraction steps quite well. Just don't forget to add a link to your analysis repository in the readme of the data repository.

**Minor Suggestions:**

- It is great you mention the authors in the readme. However, my recommendation is to include your github.com profile names and links instead of your UBC cwl profiles. These repositories are public, so your public github profiles would be more meaningful to those looking at your project.

- My recommendation is to store only raw data or metadata files in the `data/` folder. Your explanations and instructions about the data source and the data, `data_load.md` file, can be in `doc/` folder rather than the `data/` folder. However, in the end, it is up to you.

- Your commit messages are meaningful in general. Although I spot some commit messages that are version statements. Try to eliminate such messages and instead state the change you made. I would recommend checking out the post [here](https://chris.beams.io/posts/git-commit/) to improve your committing habits.

I hope this feedback is helpful in improving your project. Please let me know if you have any questions. Good luck!

**Comment by heathervant** [comment]
Thanks Ozum for the detailed feedback. I have updated our reasoning for our motivation to study this dataset on our README. We also changed the project name, and updated our cwl usernames to github,com usernames. We will also be sure to add those links you mentioned.
