### ISSUE TITLE
Feedback on milestone 1

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Taracyc_Ocean_Virus_Analysis#27]
@heathervant @HarjyotKaur 
Your readme, final report and scripts are very informative and organized. You have done a great job! 
Here are some remaining issues:

- [ ] Add a link to your report on your main readme 
- [ ] Add version information to your dependencies

Suggestions:

- In your report, alongside a snapshot, you can add summary statistics table for the variables used.
- You can include a flow chart/dependency diagram on your readme.

**Comment by HarjyotKaur** [comment]
Hi Ozum,
Thank you for your encouraging feedback.

The issues have been addressed.
A flow chart/dependency diagram has been included in the readme.

Will also, add a summary statistics statistics table for the variables in the report.

**Comment by HarjyotKaur** [comment]
Addressed All the suggestions.
