### ISSUE TITLE
Feedback on Milestone 2

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Taracyc_Ocean_Virus_Analysis#37]
@heathervant and @HarjyotKaur great job on Milestone 2! There is not much I can add. I will only suggest taking a look at http://swcarpentry.github.io/make-novice/reference. This would help make your Make code more practical. For example, you can use automatic variables and avoid some repetition.

**Comment by HarjyotKaur** [comment]
Added Automatic Variables  in Makefile ( http://swcarpentry.github.io/make-novice/reference)
